# permissions for end users to view posts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: post-viewer-role
rules:
- apiGroups:
  - cubepress.beezlabs.app
  resources:
  - posts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cubepress.beezlabs.app
  resources:
  - posts/status
  verbs:
  - get
